"""
Symptom Triage and Severity Assessment Agent.

This agent receives patient symptom text from the global workflow state,
uses a custom Python tool to parse symptoms, and updates the shared state
for downstream medical routing.
"""

from datetime import datetime
from typing import Any, Dict
import json

from app.logger_config import get_logger
from app.tools.symptom_parser_tool import symptom_parser_tool
from app.llm.ollama_client import run_ollama

logger = get_logger(__name__)


class SymptomTriageAgent:
    """
    Agent responsible for preliminary symptom triage.

    Persona:
        Clinical intake triage assistant for an e-channeling system.

    System Prompt:
        See SYSTEM_PROMPT.

    Constraints:
        - Do not diagnose diseases.
        - Do not prescribe medication.
        - Do not recommend treatment.
        - Do not invent symptoms.
        - Do not select a specialist or doctor.
        - Only produce structured triage data for downstream agents.
    """

    SYSTEM_PROMPT = """
    You are the Symptom Triage and Severity Assessment Agent in a local multi-agent e-channeling system.

    Your responsibilities:
    1. Read the patient's symptom description.
    2. Extract reported symptoms. IMPORTANT: Correct any spelling mistakes or slang into standard medical terms (e.g., "headace" -> "headache", "belly hurts" -> "abdominal pain") so the system can understand them.
    3. Determine severity (low, medium, high) and urgency (routine, priority, urgent).
    4. Identify red-flag symptoms.

    Constraints (CRITICAL):
    - DO NOT diagnose diseases.
    - DO NOT prescribe medication or recommend treatment.
    - DO NOT invent symptoms not explicitly stated by the patient.
    - DO NOT select a specialist or doctor.
    
    Output Format:
    You must return your findings in strict JSON format with the following keys:
    {
        "extracted_symptoms": ["list", "of", "all", "symptoms", "found"],
        "triage_summary_note": "A concise, 1-2 sentence clinical summary of the reported symptoms."
    }
    
    IMPORTANT: Provide ONLY the raw JSON object. Do not include markdown code blocks (like ```json). Do not add any conversational text before or after the JSON.
    """

    def __init__(self) -> None:
        """Initialize the Symptom Triage Agent."""
        self.agent_name = "SymptomTriageAgent"
        self.system_prompt = self.SYSTEM_PROMPT

    def process(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """
        Process patient symptom text and update global state.

        Args:
            state: Shared workflow state containing patient_text and location data.

        Returns:
            Updated shared state with triage results.
        """
        logger.info("%s: Starting symptom triage", self.agent_name)

        patient_text = state.get("patient_text", "")
        
        # Robust error handling for the state input
        if not patient_text or not isinstance(patient_text, str) or not patient_text.strip():
            logger.error("%s: Validation error - Symptom description cannot be empty.", self.agent_name)
            triage_result = {
                "symptoms": [],
                "severity": "low",
                "urgency": "routine",
                "red_flags": [],
                "triage_note": "Failed to generate summary.",
                "confidence": 0.85,
                "safety_disclaimer": "This is an AI-generated triage summary for specialist routing only, not a medical diagnosis.",
                "emergency_logged": False
            }
            state.update(triage_result)
            return state

        try:
            # 1. Use the SLM FIRST to extract symptoms, correct spelling, and create a clinical summary.
            llm_prompt = f"{self.SYSTEM_PROMPT}\n\nPatient Input: {patient_text}\n\nTriage JSON:"
            llm_response = run_ollama(llm_prompt)
            
            corrected_symptoms = []
            triage_note = ""
            
            if llm_response:
                try:
                    import re
                    
                    # Remove ANSI escape sequences generated by the LLM in terminal
                    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
                    cleaned_response = ansi_escape.sub('', llm_response)
                    
                    # Find everything from the first '{' to the last '}' spanning across newlines
                    json_match = re.search(r'\{.*\}', cleaned_response, re.DOTALL)
                    
                    if json_match:
                        json_str = json_match.group(0)
                        
                        # Replace newlines with spaces to avoid unescaped newline JSON errors
                        json_str = json_str.replace('\n', ' ').replace('\r', ' ')
                        
                        llm_data = json.loads(json_str, strict=False)
                        
                        if "triage_summary_note" in llm_data:
                            triage_note = llm_data["triage_summary_note"]
                        
                        # Dynamically capture ALL symptoms the LLM found and corrected
                        if "extracted_symptoms" in llm_data and isinstance(llm_data["extracted_symptoms"], list):
                            corrected_symptoms = llm_data["extracted_symptoms"]

                except Exception as e:
                    logger.warning(f"Failed to parse LLM JSON response: {e}\nRaw LLM output was: {llm_response}")

            # 2. Enrich the text with the LLM's corrected spelling so the Python tool can catch it
            enriched_text = patient_text + " " + " ".join(corrected_symptoms)

            # 3. Use the deterministic Python tool for extracting structured flags & severity safely based on enriched text
            triage_result = symptom_parser_tool(enriched_text)
            
            if triage_note:
                triage_result["triage_note"] = triage_note

            # Ensure we keep the LLM's dynamic symptoms alongside the tool's strict ones
            if corrected_symptoms:
                # Generically merge all symptoms from both the Tool and the LLM, removing duplicates.
                # Since the System Prompt strictly dictates the LLM to correct spelling to medical standards,
                # this generically captures all corrected terms without needing to hardcode typos.
                triage_result["symptoms"] = list(set(triage_result["symptoms"] + corrected_symptoms))

            # Update red flags to a meaningful message if empty
            if not triage_result["red_flags"]:
                triage_result["red_flags"] = ["No immediate life-threatening conditions detected."]

            state["symptoms"] = triage_result["symptoms"]
            state["severity"] = triage_result["severity"]
            state["urgency"] = triage_result["urgency"]
            state["red_flags"] = triage_result["red_flags"]
            state["triage_result"] = triage_result

            if not isinstance(state.get("conversation_log"), list):
                state["conversation_log"] = []

            state["conversation_log"].append(
                {
                    "agent": self.agent_name,
                    "timestamp": datetime.now().isoformat(),
                    "system_prompt_summary": (
                        "Extract symptoms, classify severity/urgency, "
                        "identify red flags, and avoid diagnosis or treatment advice."
                    ),
                    "input": {
                        "patient_text": patient_text,
                        "patient_city": state.get("patient_city"),
                    },
                    "tool_called": "symptom_parser_tool",
                    "output": triage_result,
                }
            )

            logger.info(
                "%s: Completed triage - severity=%s, urgency=%s",
                self.agent_name,
                triage_result["severity"],
                triage_result["urgency"],
            )

            return state

        except ValueError as error:
            error_message = str(error)
            logger.error("%s: Validation error - %s", self.agent_name, error_message)

            state["error"] = error_message
            state["triage_result"] = {"error": error_message}
            return state

        except Exception as error:
            error_message = f"Unexpected triage error: {error}"
            logger.exception("%s: %s", self.agent_name, error_message)

            state["error"] = error_message
            state["triage_result"] = {"error": error_message}
            return state


def create_symptom_triage_node():
    """Create a workflow-compatible symptom triage node."""
    agent = SymptomTriageAgent()
    return agent.process